import { FaFacebookF } from 'react-icons/fa';
import { FcGoogle } from 'react-icons/fc';
import { GrUserAdmin } from 'react-icons/gr';
import { IoHeart, IoHeartOutline } from 'react-icons/io5';
import {
  LuAlertCircle,
  LuBarChart3,
  LuBell,
  LuBellRing,
  LuBookmark,
  LuBookmarkPlus,
  LuChevronDown,
  LuChevronLeft,
  LuChevronRight,
  LuChevronUp,
  LuChevronsUpDown,
  LuCircleOff,
  LuContact,
  LuEye,
  LuEyeOff,
  LuHelpCircle,
  LuImage,
  LuKeyRound,
  LuLifeBuoy,
  LuLoader,
  LuLock,
  LuLogOut,
  LuMail,
  LuMenu,
  LuMoon,
  LuMoreVertical,
  LuNewspaper,
  LuPalette,
  LuPen,
  LuPlus,
  LuSearch,
  LuSendHorizonal,
  LuSettings,
  LuSun,
  LuTrash2,
  LuTrophy,
  LuUser,
  LuUserCircle,
  LuUsers,
} from 'react-icons/lu';
import { PiShareFat } from 'react-icons/pi';
import { TbCategoryPlus } from 'react-icons/tb';

export const ICONS = {
  sun: LuSun,
  moon: LuMoon,
  key: LuKeyRound,
  profile: LuUser,
  users: LuUsers,
  clubs: LuContact,
  mail: LuMail,
  contest: LuTrophy,
  palette: LuPalette,
  account: LuUserCircle,
  alert: LuAlertCircle,
  bell: LuBell,
  settings: LuSettings,
  support: LuLifeBuoy,
  logout: LuLogOut,
  help: LuHelpCircle,
  saved: LuBookmark,
  savedPlus: LuBookmarkPlus,
  admin: GrUserAdmin,
  gallery: LuImage,
  plus: LuPlus,
  categories: TbCategoryPlus,
  post: LuNewspaper,
  dashboard: LuBarChart3,
  google: FcGoogle,
  facebook: FaFacebookF,
  heartFull: IoHeart,
  heart: IoHeartOutline,
  more: LuMoreVertical,
  arrowDown: LuChevronDown,
  arrowUp: LuChevronUp,
  arrowLeft: LuChevronLeft,
  arrowRight: LuChevronRight,
  share: PiShareFat,
  send: LuSendHorizonal,
  delete: LuTrash2,
  edit: LuPen,
  block: LuCircleOff,
  lock: LuLock,
  search: LuSearch,
  menu: LuMenu,
  loader: LuLoader,
  chevrons: LuChevronsUpDown,
  notifications: LuBellRing,
  eye: LuEye,
  noEye: LuEyeOff,
};
